services:
    netchat-server:
        image: ghcr.io/tkbstudios/netchat-server-rust/netchat-server:latest
        ports:
            - "2052:2052/tcp"
            - "2053:2053/tcp"
        volumes:
          - ./config.toml:/app/config.toml
        restart: always
