name: Publish to GHCR

on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [amd64, arm64]
        include:
          - architecture: amd64
            target: x86_64-unknown-linux-gnu
          - architecture: arm64
            target: aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Check architecture
        id: arch-check
        run: echo "Architecture is ${{ matrix.architecture }}"

      - name: Build
        if: ${{ matrix.architecture == 'amd64' }}
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --locked --target ${{ matrix.target }}

      - name: Build Docker image
        if: ${{ matrix.architecture == 'amd64' }}
        run: |
          TAG=${{ github.ref_name }}
          docker build --build-arg TARGET=${{ matrix.target }} -t ghcr.io/tkbstudios/netchat-server-rust/netchat-server:${TAG} -t ghcr.io/tkbstudios/netchat-server-rust/netchat-server:latest .

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        if: ${{ matrix.architecture == 'amd64' }}
        run: |
          TAG=${{ github.ref_name }}
          docker push ghcr.io/tkbstudios/netchat-server-rust/netchat-server:${TAG}
          docker push ghcr.io/tkbstudios/netchat-server-rust/netchat-server:latest

      - name: Skip aarch64 build
        if: ${{ matrix.architecture == 'arm64' }}
        run: echo "Skipping build for aarch64"
