name: Build Rust Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target:
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev gcc-mingw-w64-x86-64

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        env:
          OPENSSL_DIR: /usr
        run: cargo build --target ${{ matrix.target }} --release

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}-build
          path: target/${{ matrix.target }}/release/

      - name: Upload release
        if: success()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/*
          file_glob: true
